version: "3.7"

services:
  nginx:
    image: nginx
    volumes:
      - type: volume
        source: nginx_log_vol
        target: /var/log/nginx/
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      frontend:
        aliases:
          - nginx


volumes:
  nginx_log_vol:

networks:
  frontend:
    driver: bridge
