---
  - name: docker_install role
    hosts: all
    become: yes
    roles:
      - docker_install

  - name: docker_nginx role
    hosts: tag_Name_nginx
    become: yes
    roles:
      - docker_nginx

  - name: Init Swarm Master
    hosts: tag_Name_master
    become: yes
    ignore_errors: yes
    tasks:
    - name: Swarm Init
      command: docker swarm init --advertise-addr {{ inventory_hostname }}

    - name: Get Worker Token
      command: docker swarm join-token worker -q
      register: worker_token

    - name: Show Worker Token
      debug: var=worker_token.stdout

  #  - name: Master Token
  #    command: docker swarm join-token manager -q
  #    register: master_token

  #  - name: Show Master Token
  #    debug: var=master_token.stdout
      #vars:
      #  stop_now: true

  - name: Join Swarm Cluster
    hosts: tag_Name_worker
    gather_facts: yes
    ignore_errors: yes
    vars:
      token: "{{ hostvars[groups['tag_Name_master'][0]]['worker_token']['stdout'] }}"
      master: "{{ hostvars[groups['tag_Name_master'][0]]['inventory_hostname'] }}"

    tasks:
      - name: Join Swarm Cluster as a Worker
        command: sudo usermod -aG docker ec2-user
        command: sudo docker swarm join --token {{ token }} {{ master }}:2377
        register: worker

      - name: Show Results
        debug: var=worker.stdout

      - name: Show Errors
        debug: var=worker.stderr

      - name: Creating directory "docker"
        file:
          path: /home/ec2-user/docker
          state: directory

      - name: Copy docker folder
        copy:
          src: ~/Documents/dockerdemo/docker/
          dest: /home/ec2-user/docker/

      - name: Building images
        command: docker build -t tomcat:v1 -f /home/ec2-user/docker/tomcat/Dockerfile /home/ec2-user/docker/tomcat


  - name: docker_stack role
    hosts: tag_Name_master
    become: yes
    roles:
      - docker_stack
